MvcApplicationCSharp5/Models/Phone.cs
using System.Collections;
using System.Collections.Generic;

namespace MvcApplicationCSharp5.Models
{
    public class Phone : Entity
    {
        public string Name { get; set; }
        public int CompanyId { get; set; }
        public int CurrencyId { get; set; }
        public decimal Price { get; set; }

        public Company Company { get; set; }
        public Currency Currency { get; set; }

        public ICollection<Order> Orders { get; set; }

        public Phone()
        {
            Orders = new List<Order>();
        }
    }
}

MvcApplicationCSharp5/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcApplicationCSharp5;
using MvcApplicationCSharp5.Models;
using MvcApplicationCSharp5.Repositories;
using MvcApplicationCSharp5.ViewModels;

namespace MvcApplicationCSharp5.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrdersRepository _ordersRepository;
        private readonly IPhoneRepository _phoneRepository;
        private readonly ICurrencyRepository _currencyRepository;

        public OrdersController(
            IOrdersRepository ordersRepository,
            IPhoneRepository phoneRepository,
            ICurrencyRepository currencyRepository)
        {
            _ordersRepository = ordersRepository;
            _phoneRepository = phoneRepository;
            _currencyRepository = currencyRepository;
        }
        //private readonly ApplicationDbContext _context;

        //public OrdersController(ApplicationDbContext context)
        //{
        //    _context = context;
        //}

        // GET: Orders
        //public async Task<IActionResult> Index()
        //{
        //    var applicationDbContext = _context.Orders.Include(o => o.Currency).Include(o => o.Phone);
        //    return View(await applicationDbContext.ToListAsync());
        //}

        // GET: Orders/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var order = await _context.Orders
        //        .Include(o => o.Currency)
        //        .Include(o => o.Phone)
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (order == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(order);
        //}

        // GET: Orders/Create
        public IActionResult Create(int? phoneId)
        {
            if (!phoneId.HasValue)
            {
                return RedirectToAction("Index", "Phones");
            }

            var phone = _phoneRepository.GetById(phoneId.Value);

            if (phone == null)
            {
                return RedirectToAction("Index", "Phones");
            }

            var orderPhoneViewModel = new OrderPhoneViewModel()
            {
                PhoneId = phone.Id,
                PhoneName = phone.Name,
                CurrenciesSelectList = new SelectList(_currencyRepository.GetAll(), "Id", "Name")
            };
            
            return View(orderPhoneViewModel);
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm] OrderPhoneViewModel model)
        {
            try
            {
                if(IsOrderAlreadyExists(model))
                    ModelState.AddModelError("Error", "такой заказ уже есть");

                if (!ModelState.IsValid)
                    return View("Create", model);

                var order = Mapper.Map<Order>(model);

                _ordersRepository.Add(order);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Error", e.Message);
                return RedirectToAction("Create", new
                {
                    phoneId = model.PhoneId
                });
            }

            return RedirectToAction("Details", "Phones", new
            {
                id = model.PhoneId
            });
        }

        private bool IsOrderAlreadyExists(OrderPhoneViewModel model)
        {
            var order = _ordersRepository.FindOrderByClientAndPhoneId(model.PhoneId, model.CustomerName,
                model.CustomerAddress);

            return order != null;
        }
    }
}

MvcApplicationCSharp5/Controllers/PhonesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcApplicationCSharp5.Enums;
using MvcApplicationCSharp5.Models;
using MvcApplicationCSharp5.Repositories;
using MvcApplicationCSharp5.ViewModels;

namespace MvcApplicationCSharp5.Controllers
{
    public class PhonesController : Controller
    {
        private readonly IPhoneRepository _phoneRepository;
        private readonly ICompanyRepository _companyRepository;
        private readonly ICurrencyRepository _currencyRepository;

        public PhonesController(
            IPhoneRepository phoneRepository,
            ICompanyRepository companyRepository,
            ICurrencyRepository currencyRepository)
        {
            if(phoneRepository == null)
                throw new ArgumentNullException(nameof(phoneRepository));
            if(companyRepository == null)
                throw new ArgumentNullException(nameof(companyRepository));
            if(currencyRepository == null)
                throw new ArgumentNullException(nameof(currencyRepository));

            _phoneRepository = phoneRepository;
            _companyRepository = companyRepository;
            _currencyRepository = currencyRepository;
        }

        // GET: Phones
        public IActionResult Index(
            string name,
            int? companyId,
            decimal? priceFrom,
            decimal? priceTo,
            SortState sortState = SortState.NameAsc,
            int page = 1)
        {
            var phones = _phoneRepository.GetAllIncludeCompanies();
            var model = new PhonesListViewModel();
            #region Filters
            if (!string.IsNullOrWhiteSpace(name))
            {
                phones = phones.Where(p => p.Name.Contains(name));
            }

            if (companyId.HasValue)
            {
                phones = phones.Where(p => p.CompanyId == companyId.Value);
            }

            if (priceFrom.HasValue)
            {
                phones = phones.Where(p => p.Price >= priceFrom.Value);
            }

            if (priceTo.HasValue)
            {
                phones = phones.Where(p => p.Price <= priceTo.Value);
            }
            #endregion

            #region Sort
            model.NameSortState = sortState == SortState.NameAsc ? SortState.NameDesc : SortState.NameAsc;
            model.CompanySortState = sortState == SortState.CompanyAsc ? SortState.CompanyDesc : SortState.CompanyAsc;
            model.PriceSortState = sortState == SortState.PriceAsc ? SortState.PriceDesc : SortState.PriceAsc;

            switch (sortState)
            {
                case SortState.NameDesc:
                    phones = phones.OrderByDescending(s => s.Name);
                    break;
                case SortState.CompanyAsc:
                    phones = phones.OrderBy(s => s.Company.Name);
                    break;
                case SortState.CompanyDesc:
                    phones = phones.OrderByDescending(s => s.Company.Name);
                    break;
                case SortState.PriceAsc:
                    phones = phones.OrderBy(s => s.Price);
                    break;
                case SortState.PriceDesc:
                    phones = phones.OrderByDescending(s => s.Price);
                    break;
                default:
                    phones = phones.OrderBy(s => s.Name);
                    break;

            }
            #endregion

            int pageSize = 3;
            var count = phones.Count();
            phones = phones.Skip((page - 1) * pageSize).Take(pageSize);

            model.Phones = phones.ToList();
            model.Companies = new SelectList(_companyRepository.GetAll(), "Id", "Name");
            model.Name = name;
            model.CompanyId = companyId;
            model.PriceTo = priceTo;
            model.PriceFrom = priceFrom;
            model.CurrentSortState = sortState;
            model.PageViewModel = new PageViewModel(count, page, pageSize);

            return View(model);
        }

        // GET: Phones/Details/5
        public IActionResult Details(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var phone = _phoneRepository.GetById(id.Value);
            if (phone == null)
            {
                return NotFound();
            }

            return View(phone);
        }

        // GET: Phones/Create
        public IActionResult Create()
        {
            var createPhoneViewModel = new CreatePhoneViewModel
            {
                Companies = new SelectList(_companyRepository.GetAll(), "Id", "Name"),
                Currencies = new SelectList(_currencyRepository.GetAll(), "Id", "Name")
            };
            return View(createPhoneViewModel);
        }

        // POST: Phones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreatePhoneViewModel model)
        {
            if (ModelState.IsValid)
            {
                var phone = Mapper.Map<Phone>(model);
                _phoneRepository.Add(phone);
                return RedirectToAction(nameof(Index));
            }

            model.Companies = new SelectList(_companyRepository.GetAll(), "Id", "Name");
            model.Currencies = new SelectList(_currencyRepository.GetAll(), "Id", "Name");
            return View(model);
        }

        // GET: Phones/Edit/5
        public IActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var phone = _phoneRepository.GetById(id.Value);
            if (phone == null)
            {
                return NotFound();
            }

            var model = Mapper.Map<EditPhoneViewModel>(phone);
            model.Companies = new SelectList(_companyRepository.GetAll(), "Id", "Name", model.CompanyId);
            model.Currencies = new SelectList(_currencyRepository.GetAll(), "Id", "Name", model.CurrencyId);
            return View(model);
        }

        // POST: Phones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditPhoneViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var phone = Mapper.Map<Phone>(model);

                    _phoneRepository.Update(phone);
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    return BadRequest(ex.Message);
                }
                return RedirectToAction(nameof(Index));
            }
            model.Companies = new SelectList(_companyRepository.GetAll(), "Id", "Name", model.CompanyId);
            model.Currencies = new SelectList(_currencyRepository.GetAll(), "Id", "Name", model.CurrencyId);
            return View(model);
        }

        // GET: Phones/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = _phoneRepository.GetById(id.Value);
            if (phone == null)
            {
                return NotFound();
            }

            return View(phone);
        }

        // POST: Phones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var phone = _phoneRepository.GetById(id);
            _phoneRepository.Delete(phone);
            return RedirectToAction(nameof(Index));
        }

        private bool PhoneExists(int id)
        {
            return _phoneRepository.GetById(id) != null;
        }
    }
}

MvcApplicationCSharp5/Views/Phones/Create.cshtml
@model MvcApplicationCSharp5.ViewModels.CreatePhoneViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Phone</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyId" class="control-label"></label>
                <select asp-for="CompanyId" class="form-control" asp-items="@Model.Companies"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CurrencyId" class="control-label"></label>
                <select asp-for="CurrencyId" class="form-control" asp-items="@Model.Currencies"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcApplicationCSharp5/Views/Phones/Delete.cshtml
@model MvcApplicationCSharp5.Models.Phone

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Phone</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcApplicationCSharp5/Views/Phones/Details.cshtml
@model MvcApplicationCSharp5.Models.Phone

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h1>Details</h1>

<div>
    <h4>Phone</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
    </dl>
</div>
<table>
    <tbody>
    <tr>
        <th>
            Дата заказа
        </th>
        <th>
            Имя заказчика
        </th>
        <th>
            Адрес доставки
        </th>
        <th>
            Валюта платежа
        </th>
    </tr>
    @{
        var orders = Model.Orders.OrderBy(o => o.DateCreated);

        foreach (var order in orders)
        {
            <tr>
                <td>@order.DateCreated.ToString("d")</td>
                <td>@order.CustomerName</td>
                <td>@order.CustomerAddress</td>
                <td>@order.Currency.Name</td>
            </tr>
        }
    }
    </tbody>
</table>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcApplicationCSharp5/Views/Phones/Edit.cshtml
@model MvcApplicationCSharp5.ViewModels.EditPhoneViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Phone</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyId" class="control-label"></label>
                <select asp-for="CompanyId" class="form-control" asp-items="@Model.Companies"></select>
                <span asp-validation-for="CompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CurrencyId" class="control-label"></label>
                <select asp-for="CurrencyId" class="form-control" asp-items="@Model.Currencies"></select>
                <span asp-validation-for="CurrencyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcApplicationCSharp5/Views/Phones/Index.cshtml
@model MvcApplicationCSharp5.ViewModels.PhonesListViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <form method="get">
        <div class="form-inline form-group">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="CompanyId" class="control-label"></label>
                <select asp-for="CompanyId" class="form-control" asp-items="@Model.Companies">
                    <option id="All" name=""></option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="PriceFrom" class="control-label"></label>
                <input asp-for="PriceFrom" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PriceTo" class="control-label"></label>
                <input asp-for="PriceTo" class="form-control" />
            </div>
            <input type="submit" value="Фильтр" class="btn btn-default" />
        </div>
    </form>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            <a asp-action="Index"
               asp-route-name="@Model.Name"
               asp-route-companyId="@Model.CompanyId"
               asp-route-priceFrom="@Model.PriceFrom"
               asp-route-priceTo="@Model.PriceTo"
               asp-route-page="@Model.PageViewModel.PageNumber"
               asp-route-sortState="@Model.NameSortState">Наименование</a>
                
        </th>
        <th>
            <a asp-action="Index"
               asp-route-name="@Model.Name"
               asp-route-companyId="@Model.CompanyId"
               asp-route-priceFrom="@Model.PriceFrom"
               asp-route-priceTo="@Model.PriceTo"
               asp-route-page="@Model.PageViewModel.PageNumber"
               asp-route-sortState="@Model.PriceSortState">Цена</a>
        </th>
        <th>
            <a asp-action="Index"
               asp-route-name="@Model.Name"
               asp-route-companyId="@Model.CompanyId"
               asp-route-priceFrom="@Model.PriceFrom"
               asp-route-priceTo="@Model.PriceTo"
               asp-route-page="@Model.PageViewModel.PageNumber"
               asp-route-sortState="@Model.CompanySortState">Производитель</a>
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Phones) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Company.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                <a asp-action="Create" asp-controller="Orders" asp-route-phoneId="@item.Id">Order</a>
            </td>
        </tr>
    }
    </tbody>
</table>
@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-name="@Model.Name"
       asp-route-companyId="@Model.CompanyId"
       asp-route-priceFrom="@Model.PriceFrom"
       asp-route-priceTo="@Model.PriceTo"
       asp-route-sortState="@Model.CurrentSortState"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-default btn">
        <i class="glyphicon glyphicon-chevron-left">Назад</i>
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Index"
       asp-route-name="@Model.Name"
       asp-route-companyId="@Model.CompanyId"
       asp-route-priceFrom="@Model.PriceFrom"
       asp-route-priceTo="@Model.PriceTo"
       asp-route-sortState="@Model.CurrentSortState"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-default btn">
        <i class="glyphicon glyphicon-chevron-right">Вперед</i>
    </a>
}